### ISSUE TITLE
Species 6811

### ISSUE THREAD

**Issue by lmguzman** [SrivastavaLab/cesabfunctionalwebsdata#7]
Heya, so the trait table has a column called num which should be taxon_num. 
Species 6811 has different traits but same name and etc. If its a difference between adult and larvae, the data provided by the trait table doesn't make it discernible.

**Comment by aammd** [comment]
@vanderleidebastiani points out that there are in fact three problematic species here:

"5176" "5226" "6811"

These are the three morphospecies of _Omicrus ingens_ x the two life stages for a total of 6 species 😓

**Comment by aammd** [comment]
After some detective work, I identified the problem. These animals present an unusual case: they are identified only to the level of subfamily, and yet we have a kind of _subspecies_ information on them -- we know their life history stage.

The problem is that both life history stages were matched to each taxon, creating three doubled rows. This is the problem that @lmguzman and @vanderleidebastiani identified.

I have resolved this by making sure that, for members of this group, they are always identified as either larva or adult in _both_ the trait table and the database itself.

Thanks to Vanderlei and Melissa for finding this error! 

|species_id |names                                                  |bwg_name       |domain    |kingdom  |phylum     |subphylum |class   |subclass |ord        |subord    |family        |subfamily     |tribe |genus |species |subspecies |functional_group |predation |realm   |micro_macro |barcode |taxon_level |taxon_name          | taxon_number| AS1| AS2| AS3| AS4| BS1| BS2| BS3| BS4| BS5| DM1| DM2| FD1| FD2| FD3| FD4| FD5| FD6| FD7| FD8| FG1| FG2| FG3| FG4| FG5| FG6| RE1| RE2| RE3| RE4| RE5| RE6| RE7| RE8| RF1| RF2| RF3| RF4| LO1| LO2| LO3| LO4| LO5| LO6| LO7| RM1| RM2| RM3| RM4| RM5| MD1| MD2| MD3| MD4| MD5| MD6| MD7| MD8| CP1| CP2| CP3| BF1| BF2| BF3| BF4|
|:----------|:------------------------------------------------------|:--------------|:---------|:--------|:----------|:---------|:-------|:--------|:----------|:---------|:-------------|:-------------|:-----|:-----|:-------|:----------|:----------------|:---------|:-------|:-----------|:-------|:-----------|:-------------------|------------:|---:|---:|---:|---:|---:|---:|---:|---:|---:|---:|---:|---:|---:|---:|---:|---:|---:|---:|---:|---:|---:|---:|---:|---:|---:|---:|---:|---:|---:|---:|---:|---:|---:|---:|---:|---:|---:|---:|---:|---:|---:|---:|---:|---:|---:|---:|---:|---:|---:|---:|---:|---:|---:|---:|---:|---:|---:|---:|---:|---:|---:|---:|---:|---:|
|5176       |Hydrophilidae sp. (adult);terrestrial black beetle sp. |Coleoptera.48a |Eukaryota |Animalia |Arthropoda |NA        |Insecta |Neoptera |Coleoptera |Polyphaga |Hydrophilidae |Sphaeridiinae |NA    |NA    |NA      |adult      |piercer          |predator  |aquatic |macro       |NA      |subfamily   |Sphaeridiinae_adult |           10|   3|   3|   2|   2|   0|   3|   1|   0|   0|   0|   3|   0|   0|   2|   0|   2|   2|   0|   0|   0|   0|   0|   0|   3|   0|   0|   0|   0|   3|   1|   0|   1|   0|   0|   0|   0|   3|   1|   0|   3|   3|   2|   0|   0|   1|   1|   1|   3|   0|   0|   0|   0|   0|   0|   3|   0|   0|   0|   3|   2|   0|   3|   0|   0|
|5226       |Hydrophilid (new);Hydrophilidae sp. (larvae)           |Coleoptera.48b |Eukaryota |Animalia |Arthropoda |NA        |Insecta |Neoptera |Coleoptera |Polyphaga |Hydrophilidae |Sphaeridiinae |NA    |NA    |NA      |larva      |engulfer         |predator  |aquatic |macro       |NA      |subfamily   |Sphaeridiinae_larva |           10|   3|   3|   2|   2|   0|   3|   1|   0|   0|   0|   3|   0|   0|   0|   3|   0|   0|   3|   1|   0|   1|   0|   0|   1|   3|   0|   0|   0|   3|   1|   0|   1|   0|   0|   0|   0|   3|   1|   0|   3|   3|   2|   0|   0|   1|   1|   1|   3|   0|   0|   0|   0|   0|   0|   3|   0|   0|   0|   3|   2|   0|   3|   0|   0|
|6811       |Sphaeridiinae.unknown.larva                            |Coleoptera.67  |Eukaryota |Animalia |Arthropoda |NA        |Insecta |Neoptera |Coleoptera |Polyphaga |Hydrophilidae |Sphaeridiinae |NA    |NA    |NA      |larva      |engulfer         |predator  |aquatic |macro       |NA      |subfamily   |Sphaeridiinae_larva |           10|   3|   3|   2|   2|   0|   3|   1|   0|   0|   0|   3|   0|   0|   0|   3|   0|   0|   3|   1|   0|   1|   0|   0|   1|   3|   0|   0|   0|   3|   1|   0|   1|   0|   0|   0|   0|   3|   1|   0|   3|   3|   2|   0|   0|   1|   1|   1|   3|   0|   0|   0|   0|   0|   0|   3|   0|   0|   0|   3|   2|   0|   3|   0|   0|
